// Dữ liệu quận/huyện của Việt Nam theo tỉnh/thành phố
export const vietnamDistricts = {
  "An Giang": [
    "Thành phố Long Xuyên",
    "Thành phố Châu Đốc",
    "Huyện An Phú",
    "Huyện Châu Phú",
    "Huyện Châu Thành",
    "Huyện Chợ Mới",
    "Huyện Phú Tân",
    "Huyện Thoại Sơn",
    "Huyện Tịnh Biên",
    "Huyện Tri Tôn",
    "Thị xã Tân Châu",
  ],
  "Bà Rịa - Vũng Tàu": [
    "Thành phố Vũng Tàu",
    "Thành phố Bà Rịa",
    "Huyện Châu Đức",
    "Huyện Côn Đảo",
    "Huyện Đất Đỏ",
    "Huyện Long Điền",
    "Huyện Tân Thành",
    "Huyện Xuyên Mộc",
  ],
  "Bạc Liêu": [
    "Thành phố Bạc Liêu",
    "Huyện Hồng Dân",
    "Huyện Phước Long",
    "Huyện Vĩnh Lợi",
    "Huyện Giá Rai",
    "Huyện Đông Hải",
    "Huyện Hoà Bình",
  ],
  "Bắc Giang": [
    "Thành phố Bắc Giang",
    "Huyện Yên Thế",
    "Huyện Tân Yên",
    "Huyện Lạng Giang",
    "Huyện Lục Nam",
    "Huyện Lục Ngạn",
    "Huyện Sơn Động",
    "Huyện Yên Dũng",
    "Huyện Việt Yên",
    "Huyện Hiệp Hoà",
  ],
  "Bắc Kạn": [
    "Thành phố Bắc Kạn",
    "Huyện Pác Nặm",
    "Huyện Ba Bể",
    "Huyện Ngân Sơn",
    "Huyện Bạch Thông",
    "Huyện Chợ Đồn",
    "Huyện Chợ Mới",
    "Huyện Na Rì",
  ],
  "Bắc Ninh": [
    "Thành phố Bắc Ninh",
    "Huyện Yên Phong",
    "Huyện Quế Võ",
    "Huyện Tiên Du",
    "Huyện Từ Sơn",
    "Huyện Gia Bình",
    "Huyện Lương Tài",
  ],
  "Bến Tre": [
    "Thành phố Bến Tre",
    "Huyện Châu Thành",
    "Huyện Chợ Lách",
    "Huyện Mỏ Cày Bắc",
    "Huyện Mỏ Cày Nam",
    "Huyện Giồng Trôm",
    "Huyện Bình Đại",
    "Huyện Ba Tri",
    "Huyện Thạnh Phú",
  ],
  "Bình Định": [
    "Thành phố Quy Nhon",
    "Huyện An Lão",
    "Huyện Hoài Ân",
    "Huyện Hoài Nhơn",
    "Huyện Phù Cát",
    "Huyện Phù Mỹ",
    "Huyện Tây Sơn",
    "Huyện Tuy Phước",
    "Huyện Vân Canh",
    "Huyện Vĩnh Thạnh",
  ],
  "Bình Dương": [
    "Thành phố Thủ Dầu Một",
    "Thành phố Dĩ An",
    "Thành phố Thuận An",
    "Huyện Bàu Bàng",
    "Huyện Dầu Tiếng",
    "Huyện Bắc Tân Uyên",
    "Huyện Bến Cát",
    "Huyện Phú Giáo",
    "Huyện Tân Uyên",
  ],
  "Bình Phước": [
    "Thành phố Đồng Xoài",
    "Huyện Bình Long",
    "Huyện Bù Đăng",
    "Huyện Bù Đốp",
    "Huyện Bù Gia Mập",
    "Huyện Chơn Thành",
    "Huyện Đồng Phú",
    "Huyện Hớn Quản",
    "Huyện Lộc Ninh",
  ],
  "Bình Thuận": [
    "Thành phố Phan Thiết",
    "Thành phố La Gi",
    "Huyện Tuy Phong",
    "Huyện Bắc Bình",
    "Huyện Hàm Thuận Bắc",
    "Huyện Hàm Thuận Nam",
    "Huyện Tánh Linh",
    "Huyện Đức Linh",
    "Huyện Hàm Tân",
    "Huyện Phú Quí",
  ],
  "Cà Mau": [
    "Thành phố Cà Mau",
    "Huyện Cái Nước",
    "Huyện Đầm Dơi",
    "Huyện Năm Căn",
    "Huyện Ngọc Hiển",
    "Huyện Phú Tân",
    "Huyện Thới Bình",
    "Huyện Trần Văn Thời",
    "Huyện U Minh",
  ],
  "Cao Bằng": [
    "Thành phố Cao Bằng",
    "Huyện Bảo Lạc",
    "Huyện Bảo Lâm",
    "Huyện Hạ Lang",
    "Huyện Hà Quảng",
    "Huyện Hoà An",
    "Huyện Nguyên Bình",
    "Huyện Quảng Uyên",
    "Huyện Thạch An",
    "Huyện Trùng Khánh",
  ],
  "Cần Thơ": [
    "Quận Ninh Kiều",
    "Quận Ô Môn",
    "Quận Bình Thuỷ",
    "Quận Cái Răng",
    "Quận Thốt Nốt",
    "Huyện Vĩnh Thạnh",
    "Huyện Cờ Đỏ",
    "Huyện Phong Điền",
    "Huyện Thới Lai",
  ],
  "Đà Nẵng": [
    "Quận Hải Châu",
    "Quận Thanh Khê",
    "Quận Sơn Trà",
    "Quận Ngũ Hành Sơn",
    "Quận Liên Chiểu",
    "Quận Cẩm Lệ",
    "Huyện Hòa Vang",
    "Huyện Hoàng Sa",
  ],
  "Đắk Lắk": [
    "Thành phố Buôn Ma Thuột",
    "Thị xã Buôn Hồ",
    "Huyện Ea H'leo",
    "Huyện Ea Súp",
    "Huyện Buôn Đôn",
    "Huyện Cư M'gar",
    "Huyện Krông Búk",
    "Huyện Krông Năng",
    "Huyện Ea Kar",
    "Huyện M'Đrắk",
    "Huyện Krông Bông",
    "Huyện Krông Pắk",
    "Huyện Krông A Na",
    "Huyện Lắk",
    "Huyện Cư Kuin",
  ],
  "Đắk Nông": [
    "Thành phố Gia Nghĩa",
    "Huyện Đăk Glong",
    "Huyện Cư Jút",
    "Huyện Đắk Mil",
    "Huyện Krông Nô",
    "Huyện Đắk Song",
    "Huyện Đắk R'Lấp",
    "Huyện Tuy Đức",
  ],
  "Điện Biên": [
    "Thành phố Điện Biên Phủ",
    "Thị xã Mường Lay",
    "Huyện Mường Nhé",
    "Huyện Mường Chà",
    "Huyện Tủa Chùa",
    "Huyện Tuần Giáo",
    "Huyện Điện Biên",
    "Huyện Điện Biên Đông",
    "Huyện Mường Ảng",
    "Huyện Nậm Pồ",
  ],
  "Đồng Nai": [
    "Thành phố Biên Hòa",
    "Thành phố Long Khánh",
    "Huyện Tân Phú",
    "Huyện Vĩnh Cửu",
    "Huyện Định Quán",
    "Huyện Trảng Bom",
    "Huyện Thống Nhất",
    "Huyện Cẩm Mỹ",
    "Huyện Long Thành",
    "Huyện Xuân Lộc",
    "Huyện Nhơn Trạch",
  ],
  "Đồng Tháp": [
    "Thành phố Cao Lãnh",
    "Thành phố Sa Đéc",
    "Huyện Tân Hồng",
    "Huyện Tân Hưng",
    "Huyện Tân Hưng",
    "Huyện Tam Nông",
    "Huyện Thanh Bình",
    "Huyện Tháp Mười",
    "Huyện Cao Lãnh",
    "Huyện Thanh Bình",
    "Huyện Lấp Vò",
    "Huyện Lai Vung",
    "Huyện Châu Thành",
  ],
  "Gia Lai": [
    "Thành phố Pleiku",
    "Thị xã An Khê",
    "Thị xã Ayun Pa",
    "Huyện KBang",
    "Huyện Đăk Đoa",
    "Huyện Chư Păh",
    "Huyện Ia Grai",
    "Huyện Mang Yang",
    "Huyện Kông Chro",
    "Huyện Đức Cơ",
    "Huyện Chư Prông",
    "Huyện Chư Sê",
    "Huyện Đăk Pơ",
    "Huyện Ia Pa",
    "Huyện Krông Pa",
    "Huyện Phú Thiện",
    "Huyện Chư Pưh",
  ],
  "Hà Giang": [
    "Thành phố Hà Giang",
    "Huyện Đồng Văn",
    "Huyện Mèo Vạc",
    "Huyện Yên Minh",
    "Huyện Quản Bạ",
    "Huyện Vị Xuyên",
    "Huyện Bắc Mê",
    "Huyện Hoàng Su Phì",
    "Huyện Xín Mần",
    "Huyện Bắc Quang",
    "Huyện Quang Bình",
  ],
  "Hà Nam": [
    "Thành phố Phủ Lý",
    "Huyện Duy Tiên",
    "Huyện Kim Bảng",
    "Huyện Thanh Liêm",
    "Huyện Bình Lục",
    "Huyện Lý Nhân",
  ],
  "Hà Nội": [
    "Quận Ba Đình",
    "Quận Hoàn Kiếm",
    "Quận Tây Hồ",
    "Quận Long Biên",
    "Quận Cầu Giấy",
    "Quận Đống Đa",
    "Quận Hai Bà Trưng",
    "Quận Hoàng Mai",
    "Quận Thanh Xuân",
    "Huyện Sóc Sơn",
    "Huyện Đông Anh",
    "Huyện Gia Lâm",
    "Quận Nam Từ Liêm",
    "Quận Bắc Từ Liêm",
    "Huyện Mê Linh",
    "Quận Hà Đông",
    "Thị xã Sơn Tây",
    "Huyện Ba Vì",
    "Huyện Phúc Thọ",
    "Huyện Đan Phượng",
    "Huyện Hoài Đức",
    "Huyện Quốc Oai",
    "Huyện Thạch Thất",
    "Huyện Chương Mỹ",
    "Huyện Thanh Oai",
    "Huyện Thường Tín",
    "Huyện Phú Xuyên",
    "Huyện Ứng Hòa",
    "Huyện Mỹ Đức",
  ],
  "Hà Tĩnh": [
    "Thành phố Hà Tĩnh",
    "Thị xã Hồng Lĩnh",
    "Huyện Hương Sơn",
    "Huyện Đức Thọ",
    "Huyện Vũ Quang",
    "Huyện Nghi Xuân",
    "Huyện Can Lộc",
    "Huyện Hương Khê",
    "Huyện Thạch Hà",
    "Huyện Cẩm Xuyên",
    "Huyện Kỳ Anh",
    "Huyện Lộc Hà",
  ],
  "Hải Dương": [
    "Thành phố Hải Dương",
    "Thành phố Chí Linh",
    "Huyện Nam Sách",
    "Huyện Kinh Môn",
    "Huyện Kim Thành",
    "Huyện Thanh Hà",
    "Huyện Cẩm Giàng",
    "Huyện Bình Giang",
    "Huyện Gia Lộc",
    "Huyện Tứ Kỳ",
    "Huyện Ninh Giang",
    "Huyện Thanh Miện",
  ],
  "Hải Phòng": [
    "Quận Hồng Bàng",
    "Quận Ngô Quyền",
    "Quận Lê Chân",
    "Quận Hải An",
    "Quận Kiến An",
    "Quận Đồ Sơn",
    "Quận Dương Kinh",
    "Huyện Thuỷ Nguyên",
    "Huyện An Dương",
    "Huyện An Lão",
    "Huyện Kiến Thuỵ",
    "Huyện Tiên Lãng",
    "Huyện Vĩnh Bảo",
    "Huyện Cát Hải",
    "Huyện Bạch Long Vĩ",
  ],
  "Hậu Giang": [
    "Thành phố Vị Thanh",
    "Thành phố Ngã Bảy",
    "Huyện Châu Thành",
    "Huyện Châu Thành A",
    "Huyện Phụng Hiệp",
    "Huyện Vị Thuỷ",
    "Huyện Long Mỹ",
    "Thị xã Long Mỹ",
  ],
  "Hòa Bình": [
    "Thành phố Hòa Bình",
    "Huyện Đà Bắc",
    "Huyện Kỳ Sơn",
    "Huyện Lương Sơn",
    "Huyện Kim Bôi",
    "Huyện Cao Phong",
    "Huyện Tân Lạc",
    "Huyện Mai Châu",
    "Huyện Lạc Sơn",
    "Huyện Yên Thủy",
    "Huyện Lạc Thủy",
  ],
  "Hưng Yên": [
    "Thành phố Hưng Yên",
    "Huyện Văn Lâm",
    "Huyện Văn Giang",
    "Huyện Yên Mỹ",
    "Huyện Mỹ Hào",
    "Huyện Ân Thi",
    "Huyện Khoái Châu",
    "Huyện Kim Động",
    "Huyện Tiên Lữ",
    "Huyện Phù Cừ",
  ],
  "Khánh Hòa": [
    "Thành phố Nha Trang",
    "Thành phố Cam Ranh",
    "Huyện Cam Lâm",
    "Huyện Vạn Ninh",
    "Huyện Ninh Hòa",
    "Huyện Khánh Vĩnh",
    "Huyện Diên Khánh",
    "Huyện Khánh Sơn",
    "Huyện Trường Sa",
  ],
  "Kiên Giang": [
    "Thành phố Rạch Giá",
    "Thành phố Hà Tiên",
    "Huyện Kiên Lương",
    "Huyện Hòn Đất",
    "Huyện Tân Hiệp",
    "Huyện Châu Thành",
    "Huyện Giồng Riềng",
    "Huyện Gò Quao",
    "Huyện An Biên",
    "Huyện An Minh",
    "Huyện Vĩnh Thuận",
    "Huyện Phú Quốc",
    "Huyện Kiên Hải",
    "Huyện U Minh Thượng",
    "Huyện Giang Thành",
  ],
  "Kon Tum": [
    "Thành phố Kon Tum",
    "Huyện Đắk Glei",
    "Huyện Ngọc Hồi",
    "Huyện Đắk Tô",
    "Huyện Kon Plông",
    "Huyện Kon Rẫy",
    "Huyện Đắk Hà",
    "Huyện Sa Thầy",
    "Huyện Tu Mơ Rông",
    "Huyện Ia H'Drai",
  ],
  "Lai Châu": [
    "Thành phố Lai Châu",
    "Huyện Tam Đường",
    "Huyện Mường Tè",
    "Huyện Sìn Hồ",
    "Huyện Phong Thổ",
    "Huyện Than Uyên",
    "Huyện Tân Uyên",
    "Huyện Nậm Nhùn",
  ],
  "Lâm Đồng": [
    "Thành phố Đà Lạt",
    "Thành phố Bảo Lộc",
    "Huyện Đam Rông",
    "Huyện Lạc Dương",
    "Huyện Lâm Hà",
    "Huyện Đơn Dương",
    "Huyện Đức Trọng",
    "Huyện Đơn Dương",
    "Huyện Đạ Tẻh",
    "Huyện Cát Tiên",
  ],
  "Lạng Sơn": [
    "Thành phố Lạng Sơn",
    "Huyện Tràng Định",
    "Huyện Bình Gia",
    "Huyện Văn Lãng",
    "Huyện Cao Lộc",
    "Huyện Văn Quan",
    "Huyện Bắc Sơn",
    "Huyện Hữu Lũng",
    "Huyện Chi Lăng",
    "Huyện Lộc Bình",
    "Huyện Đình Lập",
  ],
  "Lào Cai": [
    "Thành phố Lào Cai",
    "Huyện Bát Xát",
    "Huyện Mường Khương",
    "Huyện Si Ma Cai",
    "Huyện Bảo Thắng",
    "Huyện Bảo Yên",
    "Huyện Sa Pa",
    "Huyện Văn Bàn",
  ],
  "Long An": [
    "Thành phố Tân An",
    "Thị xã Kiến Tường",
    "Huyện Tân Hưng",
    "Huyện Vĩnh Hưng",
    "Huyện Mộc Hóa",
    "Huyện Tân Thạnh",
    "Huyện Thạnh Hóa",
    "Huyện Đức Huệ",
    "Huyện Đức Hòa",
    "Huyện Bến Lức",
    "Huyện Thủ Thừa",
    "Huyện Tân Trụ",
    "Huyện Cần Đước",
    "Huyện Cần Giuộc",
    "Huyện Châu Thành",
  ],
  "Nam Định": [
    "Thành phố Nam Định",
    "Huyện Mỹ Lộc",
    "Huyện Vụ Bản",
    "Huyện Ý Yên",
    "Huyện Nghĩa Hưng",
    "Huyện Nam Trực",
    "Huyện Trực Ninh",
    "Huyện Xuân Trường",
    "Huyện Giao Thủy",
    "Huyện Hải Hậu",
  ],
  "Nghệ An": [
    "Thành phố Vinh",
    "Thị xã Cửa Lò",
    "Thị xã Thái Hoà",
    "Huyện Quế Phong",
    "Huyện Quỳ Châu",
    "Huyện Kỳ Sơn",
    "Huyện Tương Dương",
    "Huyện Nghĩa Đàn",
    "Huyện Quỳ Hợp",
    "Huyện Quỳnh Lưu",
    "Huyện Con Cuông",
    "Huyện Tân Kỳ",
    "Huyện Anh Sơn",
    "Huyện Diễn Châu",
    "Huyện Yên Thành",
    "Huyện Đô Lương",
    "Huyện Thanh Chương",
    "Huyện Nghi Lộc",
    "Huyện Nam Đàn",
    "Huyện Hưng Nguyên",
  ],
  "Ninh Bình": [
    "Thành phố Ninh Bình",
    "Thành phố Tam Điệp",
    "Huyện Nho Quan",
    "Huyện Gia Viễn",
    "Huyện Hoa Lư",
    "Huyện Yên Khánh",
    "Huyện Kim Sơn",
    "Huyện Yên Mô",
  ],
  "Ninh Thuận": [
    "Thành phố Phan Rang-Tháp Chàm",
    "Huyện Bác Ái",
    "Huyện Ninh Sơn",
    "Huyện Ninh Hải",
    "Huyện Ninh Phước",
    "Huyện Thuận Bắc",
    "Huyện Thuận Nam",
  ],
  "Phú Thọ": [
    "Thành phố Việt Trì",
    "Thị xã Phú Thọ",
    "Huyện Đoan Hùng",
    "Huyện Hạ Hoà",
    "Huyện Thanh Ba",
    "Huyện Phù Ninh",
    "Huyện Yên Lập",
    "Huyện Cẩm Khê",
    "Huyện Tam Nông",
    "Huyện Lâm Thao",
    "Huyện Thanh Sơn",
    "Huyện Thanh Thuỷ",
    "Huyện Tân Sơn",
  ],
  "Phú Yên": [
    "Thành phố Tuy Hòa",
    "Thị xã Sông Cầu",
    "Huyện Đồng Xuân",
    "Huyện Tuy An",
    "Huyện Sơn Hòa",
    "Huyện Sông Hinh",
    "Huyện Tây Hòa",
    "Huyện Phú Hòa",
    "Huyện Đông Hòa",
  ],
  "Quảng Bình": [
    "Thành phố Đồng Hới",
    "Huyện Minh Hóa",
    "Huyện Tuyên Hóa",
    "Huyện Quảng Trạch",
    "Huyện Bố Trạch",
    "Huyện Quảng Ninh",
    "Huyện Lệ Thủy",
  ],
  "Quảng Nam": [
    "Thành phố Tam Kỳ",
    "Thành phố Hội An",
    "Huyện Tây Giang",
    "Huyện Đông Giang",
    "Huyện Đại Lộc",
    "Huyện Điện Bàn",
    "Huyện Duy Xuyên",
    "Huyện Quế Sơn",
    "Huyện Nam Giang",
    "Huyện Phước Sơn",
    "Huyện Hiệp Đức",
    "Huyện Thăng Bình",
    "Huyện Tiên Phước",
    "Huyện Bắc Trà My",
    "Huyện Nam Trà My",
    "Huyện Phú Ninh",
    "Huyện Núi Thành",
  ],
  "Quảng Ngãi": [
    "Thành phố Quảng Ngãi",
    "Huyện Bình Sơn",
    "Huyện Trà Bồng",
    "Huyện Sơn Tịnh",
    "Huyện Tư Nghĩa",
    "Huyện Sơn Hà",
    "Huyện Sơn Tây",
    "Huyện Minh Long",
    "Huyện Nghĩa Hành",
    "Huyện Mộ Đức",
    "Huyện Đức Phổ",
    "Huyện Ba Tơ",
    "Huyện Lý Sơn",
  ],
  "Quảng Ninh": [
    "Thành phố Hạ Long",
    "Thành phố Móng Cái",
    "Thành phố Cẩm Phả",
    "Thành phố Uông Bí",
    "Huyện Bình Liêu",
    "Huyện Tiên Yên",
    "Huyện Đầm Hà",
    "Huyện Hải Hà",
    "Huyện Ba Chẽ",
    "Huyện Vân Đồn",
    "Huyện Hoành Bồ",
    "Thị xã Đông Triều",
    "Thị xã Quảng Yên",
    "Huyện Cô Tô",
  ],
  "Quảng Trị": [
    "Thành phố Đông Hà",
    "Thị xã Quảng Trị",
    "Huyện Vĩnh Linh",
    "Huyện Hướng Hóa",
    "Huyện Gio Linh",
    "Huyện Đa Krông",
    "Huyện Cam Lộ",
    "Huyện Triệu Phong",
    "Huyện Hải Lăng",
    "Huyện Cồn Cỏ",
  ],
  "Sóc Trăng": [
    "Thành phố Sóc Trăng",
    "Huyện Châu Thành",
    "Huyện Kế Sách",
    "Huyện Mỹ Tú",
    "Huyện Cù Lao Dung",
    "Huyện Long Phú",
    "Huyện Mỹ Xuyên",
    "Huyện Ngã Năm",
    "Huyện Thạnh Trị",
    "Huyện Vĩnh Châu",
    "Huyện Trần Đề",
  ],
  "Sơn La": [
    "Thành phố Sơn La",
    "Huyện Quỳnh Nhai",
    "Huyện Mường La",
    "Huyện Thuận Châu",
    "Huyện Mường Sơn",
    "Huyện Sông Mã",
    "Huyện Sốp Cộp",
    "Huyện Yên Châu",
    "Huyện Mai Sơn",
    "Huyện Mộc Châu",
    "Huyện Mường Tè",
    "Huyện Vân Hồ",
  ],
  "Tây Ninh": [
    "Thành phố Tây Ninh",
    "Huyện Tân Biên",
    "Huyện Tân Châu",
    "Huyện Dương Minh Châu",
    "Huyện Châu Thành",
    "Huyện Hòa Thành",
    "Huyện Gò Dầu",
    "Huyện Bến Cầu",
    "Huyện Trảng Bàng",
  ],
  "Thái Bình": [
    "Thành phố Thái Bình",
    "Huyện Quỳnh Phụ",
    "Huyện Hưng Hà",
    "Huyện Đông Hưng",
    "Huyện Thái Thụy",
    "Huyện Tiền Hải",
    "Huyện Kiến Xương",
    "Huyện Vũ Thư",
  ],
  "Thái Nguyên": [
    "Thành phố Thái Nguyên",
    "Thành phố Sông Công",
    "Huyện Định Hóa",
    "Huyện Phú Lương",
    "Huyện Đồng Hỷ",
    "Huyện Võ Nhai",
    "Huyện Đại Từ",
    "Huyện Phú Bình",
    "Huyện Phổ Yên",
  ],
  "Thanh Hóa": [
    "Thành phố Thanh Hóa",
    "Thị xã Bỉm Sơn",
    "Thành phố Sầm Sơn",
    "Huyện Mường Lát",
    "Huyện Quan Hóa",
    "Huyện Bá Thước",
    "Huyện Quan Sơn",
    "Huyện Lang Chánh",
    "Huyện Ngọc Lặc",
    "Huyện Cẩm Thủy",
    "Huyện Thạch Thành",
    "Huyện Hà Trung",
    "Huyện Vĩnh Lộc",
    "Huyện Yên Định",
    "Huyện Thọ Xuân",
    "Huyện Thường Xuân",
    "Huyện Triệu Sơn",
    "Huyện Thiệu Hóa",
    "Huyện Hoằng Hóa",
    "Huyện Hậu Lộc",
    "Huyện Nga Sơn",
    "Huyện Như Xuân",
    "Huyện Như Thanh",
    "Huyện Nông Cống",
    "Huyện Đông Sơn",
    "Huyện Quảng Xương",
    "Huyện Tĩnh Gia",
  ],
  "Thừa Thiên Huế": [
    "Thành phố Huế",
    "Huyện Phong Điền",
    "Huyện Quảng Điền",
    "Huyện Phú Vang",
    "Thị xã Hương Thủy",
    "Thị xã Hương Trà",
    "Huyện A Lưới",
    "Huyện Phú Lộc",
    "Huyện Nam Đông",
  ],
  "Tiền Giang": [
    "Thành phố Mỹ Tho",
    "Thị xã Gò Công",
    "Thị xã Cai Lậy",
    "Huyện Tân Phú Đông",
    "Huyện Cái Bè",
    "Huyện Cai Lậy",
    "Huyện Châu Thành",
    "Huyện Chợ Gạo",
    "Huyện Gò Công Tây",
    "Huyện Gò Công Đông",
    "Huyện Tân Phước",
    "Huyện Tân Phú Đông",
  ],
  "TP Hồ Chí Minh": [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Quận Bình Thạnh",
    "Quận Tân Bình",
    "Quận Tân Phú",
    "Quận Phú Nhuận",
    "Quận Thủ Đức",
    "Quận Gò Vấp",
    "Quận Bình Tân",
    "Huyện Củ Chi",
    "Huyện Hóc Môn",
    "Huyện Bình Chánh",
    "Huyện Nhà Bè",
    "Huyện Cần Giờ",
  ],
  "Trà Vinh": [
    "Thành phố Trà Vinh",
    "Huyện Càng Long",
    "Huyện Cầu Kè",
    "Huyện Tiểu Cần",
    "Huyện Châu Thành",
    "Huyện Cầu Ngang",
    "Huyện Trà Cú",
    "Huyện Duyên Hải",
    "Thị xã Duyên Hải",
  ],
  "Tuyên Quang": [
    "Thành phố Tuyên Quang",
    "Huyện Lâm Bình",
    "Huyện Na Hang",
    "Huyện Chiêm Hóa",
    "Huyện Hàm Yên",
    "Huyện Yên Sơn",
    "Huyện Sơn Dương",
  ],
  "Vĩnh Long": [
    "Thành phố Vĩnh Long",
    "Huyện Long Hồ",
    "Huyện Mang Thít",
    "Huyện Vũng Liêm",
    "Huyện Tam Bình",
    "Thị xã Bình Minh",
    "Huyện Trà Ôn",
    "Huyện Bình Tân",
  ],
  "Vĩnh Phúc": [
    "Thành phố Vĩnh Yên",
    "Thành phố Phúc Yên",
    "Huyện Lập Thạch",
    "Huyện Tam Dương",
    "Huyện Tam Đảo",
    "Huyện Bình Xuyên",
    "Huyện Mê Linh",
    "Huyện Yên Lạc",
    "Huyện Vĩnh Tường",
    "Huyện Sông Lô",
  ],
  "Yên Bái": [
    "Thành phố Yên Bái",
    "Thị xã Nghĩa Lộ",
    "Huyện Lục Yên",
    "Huyện Văn Yên",
    "Huyện Mù Cang Chải",
    "Huyện Trấn Yên",
    "Huyện Trạm Tấu",
    "Huyện Văn Chấn",
    "Huyện Yên Bình",
  ],
};

